title:            Yongyuan Liang's Homepage
description:      Welcome to my homepage.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //chersophyte.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: chersophyte

# Owner/author information
owner:
  name:           Yongyuan Liang
  avatar:         yulia.png
  bio:            I am a Machine Learning student researcher. Currently in Carnegie Mellon University. Interested in both theoretical and empirical research.
  email:          charlotte9762@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: yongyuan-l-31462a17a
  google_scholar:
  github: Chersophyte
  zhihu: "https://www.zhihu.com/people/shang-shi-zhou/activities"
# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum
    url: /cv/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: More About Me
    url: /about/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New York
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
